name: BA_challenge
channels:
    - conda-forge
dependencies:
  - python=3.7
  - ipykernel
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - setuptools
  - xlrd
  - pip
  - pip:
      - "--editable ."
      - folium
      - geopy
      - pycountry-convert
