name: BA_challenge
dependencies:
  - python=3.7
  - ipykernel
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - setuptools
  - pip
  - pip:
      - "--editable ."
